language: java
sudo: required
dist: trusty

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu14.04 stable main"
  - sudo apt-get update -q
  - sudo apt-get install libzeroc-ice-java -y

notifications:
  slack:
    secure: IQdjoLlyS+p0NLlguni6V594nG7Yr6RI0YHJ/d19ITZ/6sGTtSxgUL1ekT8O0eBqjg7MtyPX35xioHA3QkklX5Sqh7dBCByChjegQApxTjsSRp7oB/mzaVGNbmWRXNOUEi/8INP+HAaBoHv722WHTbaYNm4ZEnhtWA0v6HpW5Fs=
